### PR TITLE
draft support for cats

### PR DESCRIPTION
**Pull request by mandubian**

### CODE REVIEW

**Comment by djspiewak** [comment]
It's really awkward to have the code duplicated across the two modules.  But at present, the only way I can think of doing this better would be to have a core module that contains `Emm`, which in turn depends on _either_ a scalaz or a cats module, which contain the implicit machiner (e.g. `Lifter`).  Either the cats module or the scalaz module could be on your classpath, and you'll have the appropriate machinery based on the relevant framework.

Is that even worth doing?  I'd almost rather just cut ties completely and port over to cats in the mainline, since my plan is to land this in a cats module and I have no real plans of contributing to scalaz.  What do you think?

**Comment by djspiewak** [comment]
Oh, another random thought…  Do you think it's worth changing the implementation of `Joiner` to be based on `flatMap` rather than `flatten`?  I think both cats and scalaz base their `Monad` type class implementations on `flatMap`, and `Emm` does the same, so basing `Joiner` on `flatten` just adds overhead.

**Comment by mandubian** [comment]
in Precepte project, we have decided to do something not nice but working: creating metacategories that rule them all :D 
https://github.com/MfgLabs/precepte/blob/master/precepte-core/src/main/scala/MetaCats.scala

I'm not a big fan of it but couldn't find anything better to factorize the majority of our code

**Comment by djspiewak** [comment]
Let's just swap over completely to Cats.  Supporting both is more trouble than it's worth.

**Comment by mandubian** [comment]
Concerning Joiner, your flatten choice is nearer the math laws but it's true that cats & scalaz prefer flatMap/bind so I'm :+1: for going to flatMap

**Comment by djspiewak** [comment]
Alrighty, I'll swap over `flatMap` once I finish my current task…

**Comment by mandubian** [comment]
I believe this would be nice as a cats module and I must say, in my current startup, I'll try to introduce it in a few places to see how it  behaves!

**Comment by mandubian** [comment]
That's great Daniel :)
and you've convinced me that calling implicits `corecurse` is quite cool because I never know how to call those implicits but you're right, this is a corecursion :D

**Comment by djspiewak** [comment]
I opened a [separate issue](https://github.com/non/cats/issues/771) against non/cats to track the inclusion of `Emm` as a cats module.

Regarding `corecurse`, I think the name mostly just came from how I was thinking about it at the time.  :-)  It's certainly nice to have a conventional name for that case archetype, since basically every "implicit engine" type is going to have at least one.

**Comment by mandubian** [comment]
In cats, the only diff is to implement `foldLeft` & `foldRight` in `Traverser`... you can keep the sample with Scalaz Task for tests but there is no equivalent for Task in cats yet...

**Comment by mandubian** [comment]
I think with Emm, you've opened a new horizon for Monads interleaving and I feel like it will be much easier to explain it & make it accept by developers with stack of effects than with Monad Transformers :)

**Comment by djspiewak** [comment]
> I think with Emm, you've opened a new horizon for Monads interleaving and I feel like it will be much easier to explain it & make it accept by developers with stack of effects than with Monad Transformers :)

I really hope so!  I always hated having to tell people, "This is how you compose effects.  No, I don't understand it either, but it's the best we have."

**Comment by mandubian** [comment]
Monad Transformers are a compromise but as often, there must be better compromises, right?

**Pull request closed without merging**
